version: "3"
services:
  chat-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - /app/node_modules
    # environment:
    #   - port=5000
    env_file:
      - ./.env